### ISSUE TITLE
Create entry point level documentation

### ISSUE THREAD

**Issue by punkto** [aindustriosa/RustyBugA#8]
topics:

1. Line follower competition rules (https://github.com/open-robosports/normativa-velocistas )
2. Generic line follower structure (differential motion, line sensing)
3. RustyBugA hardware (Available peripherals, MCU, MCU-peripherals connection)
4. RustyBugA firmware (General processes the line follower should do (line sensing, motors control, PID))

Language: English

**Comment by punkto** [comment]
let's divide this in tasks:

- [ ]  Line follower competition rules (https://github.com/open-robosports/normativa-velocistas )
- [ ]  Generic line follower structure (differential motion, line sensing)
- [ ]  RustyBugA hardware (Available peripherals, MCU, MCU-peripherals connection)
- [ ]  RustyBugA firmware (General processes the line follower should do (line sensing, motors control, PID))

**Comment by punkto** [comment]
I'm taking the "Line follower competition rules" part. Making also the docs structure

**Comment by pcounhago** [comment]
I`ll take the "RustyBugA hardware (Available peripherals, MCU, MCU-peripherals connection)" part.

**Comment by punkto** [comment]
I'll take  RustyBugA firmware

**Comment by punkto** [comment]
I think we have enough to start with :D. @eLeDe  @hmightypirate  if you have the time, please give it a look.
